apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: e2e-pipeline-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: e2e-pipeline
  params:
  - name: source-repo
    value: https://github.com/cloud-native-garage-method-cohort/tomasz-linjing-next-app.git
  - name: image-repo
    value: quay.io/tomasz_boczek/e2e-assignment
  - name: app-name
    value: next-app
  - name: app-namespace
    value: tomasz-linjing-e2e
  workspaces:
    - name: pipeline-ws1
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi