apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-pipeline
spec:
  workspaces:
    - name: pipeline-ws1 # The name of the workspace in the Pipeline
  params:
    - name: source-repo
      type: string
    - name: image-repo
      type: string
    - name: app-name
      type: string
    - name: app-namespace
      type: string
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "$(params.source-repo)"
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: pipeline-ws1
    - name: test-nextjs
      taskRef:
        name: ###
      params:
        - name: ###
          value: ###
        - name: ###
          value: ###
      workspaces:
        - name: ###
          workspace: pipeline-ws1
    - name: build
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: "$(params.image-repo)"
      workspaces:
        - name: source
          workspace: pipeline-ws1
      runAfter:
        - git-clone
    - name: create-manifests
      taskRef:
        name: create-configuration
      params:
        - name: app-name
          value: "$(params.app-name)"
        - name: commit
          value: "$(tasks.build.results.IMAGE_DIGEST)"
        - name: image-repo
          value: "$(params.image-repo)"
        - name: source-repo
          value: "$(params.source-repo)"
      workspaces:
        - name: source
          workspace: pipeline-ws1
      runAfter:
        - build
    - name: deploy
      taskRef:
        name: deploy
      params:
       - name: app-namespace
         value: "$(params.app-namespace)"
       - name: manifest
         value: "$(tasks.create-manifests.results.manifest)"
      workspaces:
        - name: source
          workspace: pipeline-ws1
      runAfter:
        - create-manifests